#
# Configurações do Eslint
env:
# utilizando module.exports e require
  commonjs: true
  es2021: true
  node: true
extends:
# Utilizando para criar a padronização do airbnb para Javascript
  - airbnb-base
parserOptions:
# Ambiente configurado para o ECMAScript 2021
  ecmaVersion: 12
ignorePatterns: ["node_modules"]
plugins: 
rules: {}
overrides: []
